### ISSUE TITLE
Importing Scan Profiles fails (creates a bug/support ticket)

### ISSUE THREAD

**Issue by Anumann** [pdq/PowerShell-Scanners#1]
Am I doing something wrong?

Thanks

AppDomain         : PDQInventoryConsole.exe
CLR Version       : 4.0.30319.42000
Comments          :  
Current AppDomain : PDQInventoryConsole.exe
Database          : C:\ProgramData\Admin Arsenal\PDQ Inventory\Database.db
Date              : 2020-04-27T21:32:46.5423359Z
Email             : ___________
Entry             : C:\Program Files (x86)\Admin Arsenal\PDQ Inventory\PDQInventoryConsole.exe
Error             : One or more errors occurred.
Error Type        : System.InvalidOperationException
License Mode      : Enterprise Mode
Manufacturer      : Dell Inc. (Precision Tower 3620)
Memory            : 16 GB (9 GB free)
PID               : 9816
Process           : PDQInventoryConsole
Product           : PDQ Inventory
SentryEnabled     : True
Service Mode      : Local
Subject           : One or more errors occurred.
System.Object     :  
Version           : 18.4.0.0
Windows           : Microsoft Windows 10 Pro (10.0.18363)

Unknown ScannerType type: PowerShell
System.InvalidOperationException
HResult: 0x80131509 Code:5385 Facility:19 Warning
------- INNER EXCEPTIONS -------
Unknown ScannerType type: PowerShell
System.InvalidOperationException
HResult: 0x80131509 Code:5385 Facility:19 Warning
   at AdminArsenal.PDQInventory.ScannerTypeManager.Get(String typeName)
   at AdminArsenal.PDQInventory.Scanner.Import(Transfer input)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at AdminArsenal.Containers.NotifyList`1.ResetWith(IEnumerable`1 items)
   at AdminArsenal.PDQInventory.ScanProfile..ctor(Transfer input)
   at AdminArsenal.PDQInventory.Importer.ImportScanProfile(Transfer input, List`1 result)
   at AdminArsenal.PDQInventory.Importer.Import(TransferMap transfer, IEnumerable`1 objectTypes, Object parent, Object context)
   at AdminArsenal.PDQInventory.Importer.Import(XElement element, IEnumerable`1 objectTypes, Object parent, Object context)
   at AdminArsenal.PDQInventory.ImporterServer.<>c__DisplayClass6_0.<BeginImportInternal>b__0(ProtocolTaskContext task)
   at AdminArsenal.Protocol.ProtocolTask`1.<.ctor>b__0_0(ProtocolTaskContext cancel)
   at AdminArsenal.Protocol.ProtocolTask.Execute()
   at System.Threading.Tasks.Task.Execute()
------- OUTER EXCEPTION -------
Unknown ScannerType type: PowerShell
System.InvalidOperationException
HResult: 0x80131509 Code:5385 Facility:19 Warning
   at AdminArsenal.ExceptionExtensions.Rethrow(Exception ex)
   at AdminArsenal.Protocol.ProtocolError.Throw()
   at System.Threading.Tasks.Task.Execute()
------- OUTER EXCEPTION -------
One or more errors occurred.
System.AggregateException
System.Object: 
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at AdminArsenal.Protocol.ProtocolTask.Wait()
   at AdminArsenal.Protocol.ProtocolTask`1.get_Result()
   at AdminArsenal.PDQInventory.ImporterProtocol.Import(IEnumerable`1 fileNames, Object parent, Object context, String[] objectTypes)
   at AdminArsenal.PDQInventory.Scanners.ScanProfilesWindow.Import_Executed(Object sender, ExecutedRoutedEventArgs e)
   at System.Windows.Input.CommandBinding.OnExecuted(Object sender, ExecutedRoutedEventArgs e)
   at System.Windows.Input.CommandManager.ExecuteCommandBinding(Object sender, ExecutedRoutedEventArgs e, CommandBinding commandBinding)
   at System.Windows.Input.CommandManager.FindCommandBinding(CommandBindingCollection commandBindings, Object sender, RoutedEventArgs e, ICommand command, Boolean execute)
   at System.Windows.Input.CommandManager.FindCommandBinding(Object sender, RoutedEventArgs e, ICommand command, Boolean execute)
   at System.Windows.Input.CommandManager.OnExecuted(Object sender, ExecutedRoutedEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Input.RoutedCommand.ExecuteImpl(Object parameter, IInputElement target, Boolean userInitiated)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by steviecoaster** [comment]
@Anumann  you have some sensitive data in the error trace, you may want to edit that out.

**Comment by Anumann** [comment]
Thanks. I worked out the issue too - I need to be running the beta version of the app, which I'm not, so the error is expected.
